[project]
name = "call_me_maybe"
version = "0.1.0"
description = "Introduction to function calling in LLMs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pydantic",
    "llm_sdk",
    "flake8>=7.3.0",
]

[tool.uv.sources]
llm_sdk = { path = "./llm_sdk", editable = true }

[tool.mypy]
strict = true
exclude = "llm_sdk"

[[tool.mypy.overrides]]
module = ["llm_sdk"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.flake8]
max-line-length = 120

[dependency-groups]
dev = [
    "mypy>=1.20.0",
]
